teleop_twist_joy:
  ros__parameters:
    require_enable_button: false
    enable_button: 9        # จากรูป /joy ปุ่มที่กดแล้วเป็น 1 คือ index 8

    axis_linear.x: 1
    scale_linear.x: 0.75

    axis_angular.yaw: 2
    scale_angular.yaw: 1.5
